### ISSUE TITLE
I see the message but voice.mozilla.org doesn't show me that recordings

### ISSUE THREAD

**Issue by Txopi** [JRMeyer/common-voice-stats#17]
If I visit voice.mozilla.org to collaborate with Basque language, I see the message in the header of the website announcing the creation of the first target segment. When I enter the speak page I should see the Basque words for numbers and yes/no, but I get the standard Basque sentences instead: https://voice.mozilla.org/eu/speak
The same happens at least with Esperanto: https://voice.mozilla.org/eo/speak

**Comment by mbransn** [comment]
@Txopi can you please file this at the Common Voice repo: https://github.com/mozilla/voice-web/issues Thanks!

**Comment by Txopi** [comment]
[Done](https://github.com/mozilla/voice-web/issues/2754), thank you.
