### ISSUE TITLE
Bashkort numbers and yes/no

### ISSUE THREAD

**Issue by AigizK** [JRMeyer/common-voice-stats#32]
0-ноль
1-бер
2-ике
3-өс
4-дүрт
5-биш
6-алты
7-ете
8-һигеҙ
9-туғыҙ
10-ун

Yes-эйе
No-юҡ

**Comment by JRMeyer** [comment]
Thanks, @AigizK ! Have these been verified by a native Bashkort speaker?

**Comment by AigizK** [comment]
yes, i am native speaker. also i am manager for bashkort language on https://pontoon.mozilla.org/ba/

**Comment by JRMeyer** [comment]
great! Glad to see bashkort tele on Common Voice:)

**Comment by JRMeyer** [comment]
https://github.com/JRMeyer/common-voice-stats/commit/588f5165d81a889f4be7a498e5c118239a329d12
